//! 读取 Kafka `client.conf` 中的 SSL（及 `bootstrap.servers`），在 **当前工作目录** 生成 `kafka.ssl.yaml`。

use std::env;
use std::ffi::OsString;
use std::fs;
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};

const OUT_FILE: &str = "kafka.ssl.yaml";
const DEFAULT_TOPIC: &str = "log_river";
const DEFAULT_KAFKA_PORT: u16 = 9092;

fn default_client_conf_path() -> PathBuf {
    resolve_oem::kafka_client_conf_path()
}

fn expect_client_conf_file(path: &Path) -> PathBuf {
    if path.is_file() {
        return path.to_path_buf();
    }
    eprintln!("kafka-ssl-gen: 不是可读文件: {}", path.display());
    std::process::exit(1);
}

fn parse_args() -> PathBuf {
    let default_path = default_client_conf_path();
    let mut it = env::args_os().skip(1);
    let a1: Option<OsString> = it.next();
    let a2: Option<OsString> = it.next();
    if a2.is_some() {
        eprintln!(
            "用法: kafka-ssl-gen [PATH]\n\
             PATH：`client.conf` 文件路径；至多一个参数。\n\
             省略 PATH 时读取: {}\n\
             在当前目录写入: {OUT_FILE}",
            default_path.display()
        );
        std::process::exit(2);
    }
    match a1 {
        None => default_path,
        Some(p) => expect_client_conf_file(Path::new(&p)),
    }
}

fn parse_kv_line(line: &str) -> Option<(&str, &str)> {
    let t = line.trim_end();
    if t.is_empty() || t.starts_with('#') || t.starts_with('!') {
        return None;
    }
    let (k, v) = t.split_once('=')?;
    let k = k.trim();
    if k.is_empty() {
        return None;
    }
    Some((k, v.trim()))
}

fn emit_kafka_yaml_key(key: &str) -> bool {
    key == "security.protocol" || key.starts_with("ssl.")
}

fn yaml_scalar(value: &str) -> String {
    if value.is_empty() {
        return "\"\"".to_string();
    }
    let reserved = matches!(
        value,
        "true" | "false" | "null" | "~" | "yes" | "no" | "on" | "off"
    );
    let plain = !reserved
        && !value.starts_with('-')
        && value.chars().all(|c| {
            c.is_ascii_alphanumeric() || matches!(c, '_' | '.' | '/' | '-' | '+')
        });
    if plain {
        return value.to_string();
    }
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn parse_brokers(value: &str) -> Vec<String> {
    value
        .split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
        .collect()
}

fn broker_port(brokers: &[String]) -> u16 {
    brokers
        .first()
        .and_then(|b| b.rsplit_once(':'))
        .and_then(|(_, port)| port.parse().ok())
        .unwrap_or(DEFAULT_KAFKA_PORT)
}

/// 仅用本机 IP 作为 broker（覆盖 client.conf 的 `bootstrap.servers`）；端口取自其首项，默认 9092。
fn build_brokers(conf_brokers: &[String]) -> Vec<String> {
    let port = broker_port(conf_brokers);
    let ip = resolve_oem::local_ip_or_empty();
    let local = if ip.is_empty() {
        format!("127.0.0.1:{port}")
    } else {
        format!("{ip}:{port}")
    };
    vec![local]
}

fn render_kafka_ssl_yaml(
    source: &Path,
    brokers: &[String],
    ssl_rows: &[(String, String)],
) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by kafka-ssl-gen from {}\n",
        source.display()
    ));
    out.push_str("sink:\n  type: kafka\n  kafka:\n");
    out.push_str("    brokers:\n");
    for b in brokers {
        out.push_str(&format!("      - {}\n", yaml_scalar(b)));
    }
    out.push_str(&format!("    topic: {DEFAULT_TOPIC}\n"));

    let has_security = ssl_rows.iter().any(|(k, _)| k == "security.protocol");
    let has_ssl = ssl_rows.iter().any(|(k, _)| k.starts_with("ssl."));
    if has_ssl && !has_security {
        out.push_str("    security.protocol: SSL\n");
    }
    for (k, v) in ssl_rows {
        out.push_str(&format!("    {}: {}\n", k, yaml_scalar(v)));
    }
    out
}

fn read_client_conf(path: &Path) -> (Vec<String>, Vec<(String, String)>) {
    let f = fs::File::open(path).unwrap_or_else(|e| {
        eprintln!("kafka-ssl-gen: 打开 {}: {e}", path.display());
        std::process::exit(1);
    });
    let mut brokers = Vec::new();
    let mut ssl_rows: Vec<(String, String)> = Vec::new();
    for line in BufReader::new(f).lines() {
        let line = line.unwrap_or_else(|e| {
            eprintln!("kafka-ssl-gen: read: {e}");
            std::process::exit(1);
        });
        if let Some((k, v)) = parse_kv_line(&line) {
            if k == "bootstrap.servers" {
                brokers = parse_brokers(v);
            } else if emit_kafka_yaml_key(k) {
                ssl_rows.push((k.to_string(), v.to_string()));
            }
        }
    }
    (brokers, ssl_rows)
}

fn main() {
    let path = parse_args();
    let (conf_brokers, ssl_rows) = read_client_conf(&path);
    let brokers = build_brokers(&conf_brokers);
    let yaml = render_kafka_ssl_yaml(&path, &brokers, &ssl_rows);
    let out = env::current_dir()
        .unwrap_or_else(|e| {
            eprintln!("kafka-ssl-gen: 获取当前目录: {e}");
            std::process::exit(1);
        })
        .join(OUT_FILE);
    fs::write(&out, yaml).unwrap_or_else(|e| {
        eprintln!("kafka-ssl-gen: 写入 {}: {e}", out.display());
        std::process::exit(1);
    });
    eprintln!("kafka-ssl-gen: 已写入 {}", out.display());
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    /// 测试内容：默认 Kafka client.conf 路径随 OEM 名变化。
    #[test]
    fn default_path_follows_oem_name() {
        let oem = resolve_oem::oem_name();
        let expected = format!("/run/{oem}_manager_agent/process/kafka/config/client.conf");
        assert_eq!(default_client_conf_path(), PathBuf::from(expected));
    }

    #[test]
    fn yaml_scalar_empty_is_quoted_empty() {
        assert_eq!(yaml_scalar(""), "\"\"");
    }

    #[test]
    fn yaml_scalar_plain_paths_and_tls() {
        assert_eq!(yaml_scalar("/opt/yotta/cert/x.jks"), "/opt/yotta/cert/x.jks");
        assert_eq!(yaml_scalar("TLSv1.3"), "TLSv1.3");
    }

    #[test]
    fn yaml_scalar_quotes_special_chars() {
        assert_eq!(yaml_scalar("a:b"), "\"a:b\"");
        assert_eq!(yaml_scalar("x@y"), "\"x@y\"");
    }

    #[test]
    fn parse_kv_trims_and_splits_first_equals() {
        assert_eq!(
            parse_kv_line("  ssl.keystore.password= ab=cd  "),
            Some(("ssl.keystore.password", "ab=cd"))
        );
    }

    #[test]
    fn broker_port_from_first_bootstrap() {
        assert_eq!(broker_port(&["10.0.0.1:19092".into()]), 19092);
        assert_eq!(broker_port(&[]), DEFAULT_KAFKA_PORT);
    }

    #[test]
    fn build_brokers_overwrites_bootstrap_with_local_only() {
        let list = build_brokers(&["10.0.0.1:19092".into(), "10.0.0.2:9092".into()]);
        assert_eq!(list.len(), 1);
        assert!(list[0].ends_with(":19092"));
        assert!(!list[0].starts_with("10.0.0."));
    }

    #[test]
    fn render_includes_sink_kafka_and_ssl_defaults() {
        let brokers = build_brokers(&["192.168.1.1:9092".into()]);
        assert_eq!(brokers.len(), 1);
        let yaml = render_kafka_ssl_yaml(
            Path::new("/tmp/client.conf"),
            &brokers,
            &[(
                "ssl.truststore.location".into(),
                "/opt/yotta/cert/truststore.jks".into(),
            )],
        );
        assert!(yaml.contains("sink:\n  type: kafka\n"));
        assert!(yaml.contains(&format!("brokers:\n      - {}\n", yaml_scalar(&brokers[0]))));
        assert!(yaml.contains("topic: log_river\n"));
        assert!(yaml.contains("security.protocol: SSL\n"));
        assert!(yaml.contains("ssl.truststore.location: /opt/yotta/cert/truststore.jks\n"));
    }

    #[test]
    fn read_client_conf_extracts_bootstrap_and_ssl() {
        let dir = std::env::temp_dir().join(format!("kafka-ssl-gen-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join("client.conf");
        let mut f = fs::File::create(&path).unwrap();
        writeln!(f, "bootstrap.servers=10.0.0.1:9092,10.0.0.2:9092").unwrap();
        writeln!(f, "security.protocol=SSL").unwrap();
        writeln!(f, "ssl.truststore.location=/opt/cert/ts.jks").unwrap();
        let (brokers, rows) = read_client_conf(&path);
        assert_eq!(brokers.len(), 2);
        assert!(rows.iter().any(|(k, _)| k == "security.protocol"));
        let _ = fs::remove_dir_all(&dir);
    }
}
