[book]
title = "logkit"
description = "日志调试工具包"
authors = ["ww"]
language = "zh-Hans"

[build]
build-dir = "book"

[output.html]
site-url = "/logkit/"
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["modern-dot-theme.css"]

[preprocessor]

[preprocessor.modern-dot]
command = "mdbook-modern-dot"
themed-output = true
theme-file = "themes/default.toml"
